BB_CONF_FRAGMENT_SUMMARY = "Generowanie osobnego archiwum z symbolami debugowymi."
BB_CONF_FRAGMENT_DESCRIPTION = "Obok obrazu powstaje drugi rootfs zawierajacy symbole debugowe \
(pakiety -dbg), spakowany do tar.bz2. Pozwala debugowac binarke z urzadzenia przez gdb na hoscie, \
nie powiekszajac przy tym samego obrazu. \
"

IMAGE_GEN_DEBUGFS = "1"
IMAGE_FSTYPES_DEBUGFS = "tar.bz2"
